"use client";

import { useState } from "react";
import { Info, Warning } from "@phosphor-icons/react";
import { Chip, Eyebrow } from "@/components/ui/primitives";
import type { WorkedExample } from "@/lib/data";
import { Reveal, Section } from "@/components/landing/reveal";
import { cn } from "@/lib/cn";

/**
 * The argument of the whole site, done to one real document.
 *
 * A DOCX with two merged cells goes to Markdown. GFM pipe syntax has no colspan, so there
 * are exactly two honest outcomes, and MarkForge implements both and names each: keep the
 * table as HTML and lose nothing, or flatten it and report the loss. The competing behaviour,
 * which is the default nearly everywhere else, is to flatten it and say nothing.
 *
 * Both panels are generated by `scripts/prepare-assets.mjs` running the real engine at build
 * time, and that script fails the build if either diagnostic stops appearing. Nothing on this
 * page is a screenshot of a thing that used to be true.
 */
export function DiagnosticsExample({
  asHtml,
  flattened,
}: {
  asHtml: WorkedExample;
  flattened: WorkedExample;
}) {
  const [mode, setMode] = useState<"auto" | "gfm">("auto");
  const example = mode === "auto" ? asHtml : flattened;
  const headline = example.diagnostics.find((d) => d.code.startsWith("MF-RENDER"));

  return (
    <Section className="rule-t py-16 lg:py-24">
      <Reveal>
        <Eyebrow>Nothing is lost silently</Eyebrow>
        <h2 className="max-w-3xl text-3xl font-semibold tracking-tight text-ink md:text-4xl">
          A merged table cell cannot survive a pipe table. There are two honest answers, and
          neither of them is silence.
        </h2>
        <p className="mt-4 max-w-prose text-[15px] leading-relaxed text-ink-muted">
          This is a real Word document from the corpus, converted here at build time. Switch
          the option and watch both the output and the diagnostic change.
        </p>
      </Reveal>

      <Reveal delay={0.06}>
        <div className="mt-10 flex flex-wrap items-center gap-2">
          <Toggle
            active={mode === "auto"}
            onClick={() => setMode("auto")}
            label="tables: auto"
            note="the default"
          />
          <Toggle
            active={mode === "gfm"}
            onClick={() => setMode("gfm")}
            label="tables: gfm"
            note="force pipe syntax"
          />
        </div>

        <div className="mt-6 grid gap-5 lg:grid-cols-[minmax(0,1fr)_minmax(0,26rem)]">
          <div className="overflow-hidden rounded-panel border border-rule bg-surface">
            <div className="rule-b flex h-9 items-center gap-2 px-3">
              <span className="font-mono text-[10px] uppercase tracking-[0.14em] text-ink-faint">
                tables-merged-horizontal.docx to Markdown
              </span>
              <Chip mono tone="quiet">
                {example.output.length} B
              </Chip>
            </div>
            <pre className="max-h-[340px] overflow-auto whitespace-pre p-3 font-mono text-[11px] leading-relaxed text-ink">
              {example.output}
            </pre>
          </div>

          <div className="flex flex-col gap-4">
            {headline ? (
              <div
                className={cn(
                  "rounded-panel border p-4",
                  headline.lossy ? "border-ember bg-ember-wash" : "border-rule bg-surface",
                )}
              >
                <div className="flex items-center gap-2">
                  {headline.lossy ? (
                    <Warning size={14} className="text-ember" />
                  ) : (
                    <Info size={14} className="text-ink-faint" />
                  )}
                  <span className="font-mono text-[12px] text-ink">{headline.code}</span>
                  {headline.lossy ? (
                    <Chip tone="accent">information lost</Chip>
                  ) : (
                    <Chip tone="neutral">nothing lost</Chip>
                  )}
                </div>
                <p className="mt-2.5 text-[12px] leading-relaxed text-ink">{headline.message}</p>
              </div>
            ) : null}

            <div className="rounded-panel border border-rule bg-surface p-4">
              <h3 className="font-mono text-[10px] uppercase tracking-[0.14em] text-ink-faint">
                What changed
              </h3>
              <p className="mt-2.5 text-[12px] leading-relaxed text-ink-muted">
                {mode === "auto"
                  ? "The table is written as raw HTML. HTML blocks are CommonMark, the reader parses it back into the same tree, and both merges survive. You pay readability only where the alternative is losing data."
                  : "The table is written as pipe syntax. The two merges become empty cells and cannot be recovered. The diagnostic carries lossy: true, which is what makes the loss greppable rather than something you find in a review three weeks later."}
              </p>
            </div>
          </div>
        </div>
      </Reveal>
    </Section>
  );
}

function Toggle({
  active,
  onClick,
  label,
  note,
}: {
  active: boolean;
  onClick: () => void;
  label: string;
  note: string;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={cn(
        "rounded-panel border px-3 py-2 text-left transition-colors",
        active ? "border-ember bg-ember-wash" : "border-rule hover:bg-sunken",
      )}
    >
      <span className={cn("block font-mono text-[12px]", active ? "text-ember" : "text-ink")}>
        {label}
      </span>
      <span className="mt-0.5 block text-[11px] text-ink-muted">{note}</span>
    </button>
  );
}
