import { Reveal, Section } from "@/components/landing/reveal";
import { ADR } from "@/lib/links";

/**
 * A page the engine actually produced.
 *
 * Generated by `scripts/prepare-assets.mjs` at build time from `fixtures/md/clean-report.md`,
 * through the same Typst markup, the same compiler and the same five faces the PDF writer
 * uses. It is SVG rather than a raster because it is then text: a reader who suspects it is a
 * mockup can open it and read the glyph positions.
 *
 * The four limits sit beside it rather than under a link. Three of them are the difference
 * between what this renderer is and what a reader would assume it is, and a page that showed
 * the output without them would be selling the assumption.
 */
const LIMITS = [
  {
    head: "Latin and mono only",
    body: "Libertinus Serif and DejaVu Sans Mono, about 1.6 MB. CJK, emoji and Arabic are outside that set. Rather than reaching for a font on your machine, which would make output depend on the machine, a gate reports the gap.",
  },
  {
    head: "Images are not embedded",
    body: "Alt text is written where the image was, with a diagnostic saying so.",
  },
  {
    head: "Style profiles do not reach it",
    body: "The decision record promises a template per profile and none exists yet, so all three profiles render identically. Offering a profile selector here would advertise a distinction that does not exist.",
  },
  {
    head: "The round-trip score is joint",
    body: "Markdown to PDF and back measures the writer and the reader together. It is never a score for this renderer alone.",
  },
];

export function RenderedPage() {
  return (
    <Section className="rule-t py-16 lg:py-24">
      <Reveal>
        <h2 className="max-w-2xl text-3xl font-semibold tracking-tight text-ink md:text-4xl">
          The PDF writer, and the four things it will not do.
        </h2>
      </Reveal>

      <div className="mt-12 grid items-start gap-12 lg:grid-cols-[minmax(0,5fr)_minmax(0,6fr)] lg:gap-16">
        <Reveal>
          <figure>
            {/*
              Not next/image: this is a vector the browser can draw at any size, and running
              it through a raster optimiser would be strictly worse. `unoptimized` is set
              globally for the same reason there is no photography here at all.
            */}
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src="/markforge/rendered-page.svg"
              alt="The first page of clean-report.md rendered to PDF: a heading, body paragraphs, a bulleted list and a table, set in Libertinus Serif."
              width={596}
              height={842}
              className="w-full rounded-panel border border-rule bg-white shadow-[0_20px_50px_-24px_rgb(var(--shadow-tint)/0.35)]"
            />
            <figcaption className="mt-3 font-mono text-[11px] text-ink-faint">
              fixtures/md/clean-report.md, compiled during this site&apos;s build
            </figcaption>
          </figure>
        </Reveal>

        <Reveal delay={0.06}>
          <dl className="space-y-7">
            {LIMITS.map((l) => (
              <div key={l.head}>
                <dt className="text-[15px] font-medium text-ink">{l.head}</dt>
                <dd className="mt-1.5 max-w-prose text-[13px] leading-relaxed text-ink-muted">
                  {l.body}
                </dd>
              </div>
            ))}
          </dl>

          <a
            href={ADR.pdfEngine}
            target="_blank"
            rel="noreferrer noopener"
            className="mt-8 inline-block text-[13px] text-ember underline-offset-4 hover:underline"
          >
            Why Typst, and what was rejected
          </a>
        </Reveal>
      </div>
    </Section>
  );
}
