/**
 * @markforge/fidelity — measurement, and the baseline gate.
 *
 * A package rather than test code because brief §3.4 makes fidelity a product
 * capability: `check` and `diff` reach it, not just CI. Recorded as a deviation
 * from the brief's §9 package layout in docs/OPEN_QUESTIONS.md §7a.
 */
import { textContent, type AnyNode, type MarkForgeDocument } from "@markforge/ir";
import {
  structuralSimilarity,
  textSimilarity,
  tableSimilarity,
  spanSimilarity,
  type StructuralScore,
  type TextScore,
  type TableScore,
} from "./metrics.js";

export interface FidelityScore {
  structural: StructuralScore;
  text: TextScore;
  table: TableScore;
  spans: { precision: number; recall: number; f1: number };
}

export function compare(expected: MarkForgeDocument, actual: MarkForgeDocument): FidelityScore {
  const a = expected.body as unknown as AnyNode;
  const b = actual.body as unknown as AnyNode;
  return {
    structural: structuralSimilarity(a, b),
    text: textSimilarity(textContent(a), textContent(b)),
    table: tableSimilarity(a, b),
    spans: spanSimilarity(a, b),
  };
}

// ---------------------------------------------------------------------------
// Baselines (ADR-0010)
// ---------------------------------------------------------------------------

export interface BaselineEntry {
  fixture: string;
  loop: string;
  structural: number;
  textSensitive: number;
  textInsensitive: number;
  tableF1: number;
  tableContentF1: number;
  spanF1: number;
}

export interface Baselines {
  version: number;
  /** Absolute tolerance. A score may drop by at most this much before CI fails. */
  tolerance: number;
  entries: BaselineEntry[];
}

export interface Regression {
  fixture: string;
  loop: string;
  metric: string;
  baseline: number;
  measured: number;
  delta: number;
}

export interface BaselineComparison {
  regressions: Regression[];
  improvements: Regression[];
  missing: string[];
  added: string[];
}

/**
 * Compares measurements against committed baselines.
 *
 * Improvements are reported too, and this is not symmetry for its own sake: a score
 * that jumps is as likely to mean the *metric* broke as that the converter improved,
 * and an unexplained improvement deserves the same look as a regression.
 */
export function compareToBaselines(
  baselines: Baselines,
  measured: BaselineEntry[],
): BaselineComparison {
  const key = (e: { fixture: string; loop: string }): string => `${e.fixture}::${e.loop}`;
  const byKey = new Map(baselines.entries.map((e) => [key(e), e]));
  const measuredKeys = new Set(measured.map(key));

  const regressions: Regression[] = [];
  const improvements: Regression[] = [];

  const METRICS: (keyof BaselineEntry)[] = [
    "structural", "textSensitive", "textInsensitive", "tableF1", "tableContentF1", "spanF1",
  ];

  for (const m of measured) {
    const base = byKey.get(key(m));
    if (!base) continue;
    for (const metric of METRICS) {
      const baseline = base[metric] as number;
      const value = m[metric] as number;
      if (typeof baseline !== "number" || typeof value !== "number") continue;
      const delta = value - baseline;
      const record: Regression = {
        fixture: m.fixture, loop: m.loop, metric: String(metric), baseline, measured: value, delta,
      };
      if (delta < -baselines.tolerance) regressions.push(record);
      else if (delta > baselines.tolerance) improvements.push(record);
    }
  }

  return {
    regressions,
    improvements,
    missing: [...byKey.keys()].filter((k) => !measuredKeys.has(k)),
    added: [...measuredKeys].filter((k) => !byKey.has(k)),
  };
}

/**
 * Renders the FIDELITY.md table.
 *
 * **There is no row-suppression mechanism here, deliberately.** Every measured
 * fixture appears. A report that can hide its worst rows is marketing, and the
 * absence of a filter is the only thing that makes the numbers worth reading.
 */
export function renderFidelityMarkdown(
  entries: BaselineEntry[],
  meta: { generatedFrom: string; corpusSize: number },
): string {
  const sorted = [...entries].sort(
    (a, b) => a.fixture.localeCompare(b.fixture) || a.loop.localeCompare(b.loop),
  );

  const pct = (n: number): string => (n < 0 ? "n/a" : (n * 100).toFixed(1) + "%");

  const lines: string[] = [
    "# Fidelity",
    "",
    "Measured, not claimed. Generated by `pnpm fidelity` from the golden corpus;",
    "every measured fixture appears, and there is no mechanism to omit a row.",
    "",
    `Corpus: ${meta.corpusSize} fixture(s). Source: ${meta.generatedFrom}.`,
    "",
    "| Fixture | Loop | Structural | Text (ws-sensitive) | Text (ws-insensitive) | Table F1 | Table content F1 | Span F1 |",
    "| --- | --- | --: | --: | --: | --: | --: | --: |",
  ];

  for (const e of sorted) {
    lines.push(
      `| ${e.fixture} | ${e.loop} | ${pct(e.structural)} | ${pct(e.textSensitive)} | ` +
        `${pct(e.textInsensitive)} | ${pct(e.tableF1)} | ${pct(e.tableContentF1)} | ${pct(e.spanF1)} |`,
    );
  }

  if (sorted.length > 0) {
    const mean = (get: (e: BaselineEntry) => number): number => {
      const values = sorted.map(get).filter((v) => v >= 0);
      return values.length === 0 ? -1 : values.reduce((a, b) => a + b, 0) / values.length;
    };
    lines.push(
      `| **mean** | | ${pct(mean((e) => e.structural))} | ${pct(mean((e) => e.textSensitive))} | ` +
        `${pct(mean((e) => e.textInsensitive))} | ${pct(mean((e) => e.tableF1))} | ` +
        `${pct(mean((e) => e.tableContentF1))} | ${pct(mean((e) => e.spanF1))} |`,
    );
  }

  lines.push(
    "",
    "## How to read these",
    "",
    "**Structural** is `1 - TED/(|T1|+|T2|)` over Zhang–Shasha ordered tree edit distance,",
    "where node labels carry type plus meaning-changing attributes but *not* text — text is",
    "the next column's job, and folding it in here would double-count one error.",
    "",
    "**Text** is grapheme-cluster Levenshtein, reported in both variants because the gap",
    "between them is itself the diagnostic: a large gap means whitespace changed and content",
    "did not.",
    "",
    "**Table F1** keys cells on `(rowStart, colStart, rowSpan, colSpan, text)`; **content F1**",
    "drops the spans. A high content score beside a low full score says one specific thing:",
    "merged cells are being flattened.",
    "",
    "**Span F1** compares inline marks as offset ranges rather than tree positions, so",
    "`<strong><em>x</em></strong>` and `<em><strong>x</strong></em>` compare equal — as they",
    "look to a reader.",
    "",
    "## Where the low numbers come from",
    "",
    "Some rows are low because a target format genuinely cannot express the construct, not",
    "because the conversion is broken. They are listed here so a reader does not have to guess",
    "which is which — and so that a row moving *off* this list is visible.",
    "",
    "- **Any loop through Markdown on a table with merged cells.** Markdown has no rowspan or",
    "  colspan. The cells survive, the merges do not, which is why table F1 drops while",
    "  content F1 stays high. `fixtures/html/spans-ground-truth.html` exists to measure that",
    "  gap, not to pass.",
    "- **html to docx to html, on text.** Constructs with no DOCX equivalent — description",
    "  lists, captions bound to an image — degrade to the nearest available structure, each",
    "  with a diagnostic.",
    "- **Structural scores in the 85 to 95 band through DOCX.** The round trip adds and removes",
    "  wrapper nodes: a list item gains a paragraph, a cell loses one. The text is intact and",
    "  the tree shape differs by a few nodes.",
    "",
    "A low score for a reason *not* listed here is a defect. Fix it, or add it here with its",
    "reason — those are the only two honest options.",
    "",
  );

  return lines.join("\n");
}

export {
  structuralSimilarity,
  textSimilarity,
  tableSimilarity,
  spanSimilarity,
  treeEditDistance,
  levenshtein,
  graphemes,
  extractCells,
  extractSpans,
} from "./metrics.js";
export type { StructuralScore, TextScore, TableScore, TableCell, InlineSpan } from "./metrics.js";
